import test from 'node:test';
import assert from 'node:assert/strict';
import Booking from '../models/Booking.js';
import Driver from '../models/Driver.js';
import { BLOCKING_STATUSES, assertDriverBookable, statusReleasesAvailability } from '../services/bookingRules.js';
import { assertAdminCommissionAction, assertCommissionSubmissionAllowed, canGenerateCommission, commissionStatusAfterRejection, determineCommissionStanding } from '../services/commissionRules.js';
import { normalizeNic, protectDriverIdentity, validateIdentityConfiguration } from '../services/driverIdentityService.js';

test('new booking defaults to pending without gateway payment',()=>assert.equal(new Booking().status,'pending'));
test('confirmed booking keeps its date lock',()=>assert.ok(BLOCKING_STATUSES.includes('confirmed')));
test('rejected booking releases its date lock',()=>assert.equal(statusReleasesAvailability('rejected'),true));
test('cancelled booking releases its date lock',()=>assert.equal(statusReleasesAvailability('cancelled'),true));
test('only confirmed bookings are commission eligible',()=>{assert.equal(canGenerateCommission('confirmed'),true);assert.equal(canGenerateCommission('cancelled'),false);assert.equal(canGenerateCommission('rejected'),false)});
test('due commission does not restrict early',()=>assert.equal(determineCommissionStanding([{status:'due'}]),'due'));
test('overdue commission restricts driver',()=>assert.equal(determineCommissionStanding([{status:'overdue'}]),'restricted'));
test('late submitted proof remains restricted until verified',()=>assert.equal(determineCommissionStanding([{status:'payment_submitted',overdueAt:new Date()}]),'restricted'));
test('paid commission clears standing when no overdue remains',()=>assert.equal(determineCommissionStanding([{status:'paid'}]),'clear'));
test('one remaining overdue commission keeps standing restricted',()=>assert.equal(determineCommissionStanding([{status:'paid'},{status:'overdue'}]),'restricted'));
test('driver can submit only due or overdue commission proof',()=>{assert.doesNotThrow(()=>assertCommissionSubmissionAllowed({status:'due'}));assert.throws(()=>assertCommissionSubmissionAllowed({status:'paid'}),/cannot accept/)});
test('admin approval requires submitted proof',()=>assert.throws(()=>assertAdminCommissionAction({status:'due'},'approve'),/submitted/));
test('admin rejection restores status based on current deadline',()=>{const now=new Date('2026-01-02');assert.equal(commissionStatusAfterRejection('2026-01-01',now),'overdue');assert.equal(commissionStatusAfterRejection('2026-01-03',now),'due')});
test('waiver and dispute require a reason',()=>{assert.throws(()=>assertAdminCommissionAction({status:'due'},'waive'),/reason/);assert.throws(()=>assertAdminCommissionAction({status:'due'},'dispute'),/reason/)});
test('dispute resolution allows only documented states',()=>{assert.doesNotThrow(()=>assertAdminCommissionAction({status:'disputed'},'resolve',{resolution:'due'}));assert.throws(()=>assertAdminCommissionAction({status:'disputed'},'resolve',{resolution:'overdue'}),/Resolution/)});
test('restricted or identity-pending driver is not bookable',()=>{assert.throws(()=>assertDriverBookable({availability:true,verificationStatus:'verified',identityVerificationRequired:false,commissionStanding:'restricted',accountStatus:'active'}),/restricted/);assert.throws(()=>assertDriverBookable({availability:true,verificationStatus:'verified',identityVerificationRequired:true,commissionStanding:'clear',accountStatus:'active'}),/unverified/)});
test('verified available clear driver is bookable',()=>assert.doesNotThrow(()=>assertDriverBookable({availability:true,verificationStatus:'verified',identityVerificationRequired:false,commissionStanding:'clear',accountStatus:'active'})));
test('both supported Sri Lankan NIC formats validate',()=>{assert.equal(normalizeNic('901234567v'),'901234567V');assert.equal(normalizeNic('200012345678'),'200012345678')});
test('invalid Sri Lankan NIC is rejected',()=>assert.throws(()=>normalizeNic('ABC123'),/valid Sri Lankan NIC/));
test('identity HMAC and encryption keys are required',()=>{const oldHmac=process.env.DRIVER_IDENTITY_HMAC_KEY,oldEncryption=process.env.DRIVER_IDENTITY_ENCRYPTION_KEY;delete process.env.DRIVER_IDENTITY_HMAC_KEY;delete process.env.DRIVER_IDENTITY_ENCRYPTION_KEY;assert.throws(validateIdentityConfiguration,/HMAC/);process.env.DRIVER_IDENTITY_HMAC_KEY=oldHmac;process.env.DRIVER_IDENTITY_ENCRYPTION_KEY=oldEncryption});
test('same identity normalizes to same retained unique fingerprints',()=>{process.env.DRIVER_IDENTITY_HMAC_KEY='test-hmac-key-that-is-definitely-long-enough';process.env.DRIVER_IDENTITY_ENCRYPTION_KEY=Buffer.alloc(32,7).toString('base64');const a=protectDriverIdentity({nic:'901234567V',drivingLicence:'B-1234567'}),b=protectDriverIdentity({nic:'901 234 567 v',drivingLicence:'b1234567'});assert.equal(a.nicFingerprint,b.nicFingerprint);assert.equal(a.drivingLicenceFingerprint,b.drivingLicenceFingerprint);const unique=Driver.schema.indexes().filter(([,options])=>options.unique).map(([fields])=>Object.keys(fields)[0]);assert.ok(unique.includes('nicFingerprint'));assert.ok(unique.includes('drivingLicenceFingerprint'))});
