import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'crypto';
import Payment from '../models/Payment.js';
import Payout from '../models/Payout.js';
import Refund from '../models/Refund.js';
import { calculateBookingMoney, fromMinorUnits, getCommissionRateBps, toMinorUnits } from '../services/payments/money.js';
import { verifyNotification } from '../services/payments/providers/payhere.provider.js';
import { assertTransitionAllowed } from '../services/bookingRules.js';
import { assertCheckoutAllowed, assertPayoutTransition, assertRefundAllowed } from '../services/payments/financialRules.js';

process.env.PAYHERE_MODE='sandbox';process.env.PAYHERE_MERCHANT_ID='merchant-1';process.env.PAYHERE_MERCHANT_SECRET='secret';process.env.PAYHERE_RETURN_URL='http://localhost:5173/payment/return';process.env.PAYHERE_CANCEL_URL='http://localhost:5173/payment/cancel';process.env.PAYHERE_NOTIFY_URL='https://example.test/api/payments/payhere/notify';
const md5=(v)=>crypto.createHash('md5').update(v).digest('hex').toUpperCase();
const payment={providerOrderId:'CE-TEST',currency:'LKR',travelerTotal:102000};
const callback=(overrides={})=>{const p={merchant_id:'merchant-1',order_id:'CE-TEST',payhere_amount:'1020.00',payhere_currency:'LKR',status_code:'2',payment_id:'PH-1',...overrides};p.md5sig=md5(`${p.merchant_id}${p.order_id}${p.payhere_amount}${p.payhere_currency}${p.status_code}${md5('secret')}`);return p};
test('money is represented in integer LKR minor units',()=>{assert.equal(toMinorUnits(12.34),1234);assert.equal(fromMinorUnits(1234),12.34)});
test('commission calculation uses configured 2 percent',()=>{process.env.PLATFORM_COMMISSION_RATE='0.02';assert.deepEqual(calculateBookingMoney({dailyRate:10000,numberOfDays:3}),{currency:'LKR',driverDailyRate:1000000,driverSubtotal:3000000,platformCommissionRateBps:200,platformCommissionAmount:60000,travelerTotal:3060000})});
test('commission snapshot remains unchanged when configuration changes',()=>{process.env.PLATFORM_COMMISSION_RATE='0.02';const snapshot=calculateBookingMoney({dailyRate:100,numberOfDays:1});process.env.PLATFORM_COMMISSION_RATE='0.05';assert.equal(snapshot.platformCommissionRateBps,200);assert.equal(snapshot.platformCommissionAmount,200)});
test('invalid callback signature is rejected',()=>assert.throws(()=>verifyNotification({...callback(),md5sig:'BAD'},payment),/signature/));
test('invalid merchant is rejected',()=>assert.throws(()=>verifyNotification(callback({merchant_id:'other'}),payment),/merchant/));
test('wrong amount is rejected',()=>assert.throws(()=>verifyNotification(callback({payhere_amount:'999.00'}),payment),/amount/));
test('wrong currency is rejected',()=>assert.throws(()=>verifyNotification(callback({payhere_currency:'USD'}),payment),/currency/));
test('valid callback maps to paid',()=>assert.equal(verifyNotification(callback(),payment).status,'paid'));
test('failed callback never maps to paid',()=>assert.equal(verifyNotification(callback({status_code:'-2'}),payment).status,'failed'));
test('pending cannot skip acceptance and become confirmed',()=>assert.throws(()=>assertTransitionAllowed('pending','confirmed'),/cannot move/));
test('accepted booking can be confirmed only by payment workflow',()=>assert.doesNotThrow(()=>assertTransitionAllowed('accepted','confirmed')));
test('payment provider order ID has a unique database index',()=>assert.ok(Payment.schema.indexes().some(([fields,options])=>fields.providerOrderId===1&&options.unique)));
test('refund idempotency key has a unique database index',()=>assert.ok(Refund.schema.indexes().some(([fields,options])=>fields.idempotencyKey===1&&options.unique)));
test('one payout per booking is enforced',()=>assert.ok(Payout.schema.indexes().some(([fields,options])=>fields.booking===1&&options.unique)));
test('invalid commission configuration fails safely',()=>{process.env.PLATFORM_COMMISSION_RATE='2';assert.throws(()=>getCommissionRateBps(),/between/);process.env.PLATFORM_COMMISSION_RATE='0.02'});
test('traveler cannot initiate another traveler booking payment',()=>assert.throws(()=>assertCheckoutAllowed({booking:{user:'owner',status:'accepted'},travelerId:'other'}),/not found/));
test('payment cannot start before driver accepts',()=>assert.throws(()=>assertCheckoutAllowed({booking:{user:'owner',status:'pending'},travelerId:'owner'}),/accept/));
test('already paid booking cannot be paid twice',()=>assert.throws(()=>assertCheckoutAllowed({booking:{user:'owner',status:'accepted',paymentStatus:'paid'},travelerId:'owner'}),/already paid/));
test('expired accepted booking cannot be paid',()=>assert.throws(()=>assertCheckoutAllowed({booking:{user:'owner',status:'accepted',paymentDueAt:new Date(0)},travelerId:'owner'}),/expired/));
test('refund cannot exceed payment total',()=>assert.throws(()=>assertRefundAllowed({payment:{status:'paid',travelerTotal:1000},amount:1001}),/exceeds/));
test('duplicate refund total is included in limit',()=>assert.throws(()=>assertRefundAllowed({payment:{status:'partially_refunded',travelerTotal:1000},amount:600,alreadyRefunded:500}),/exceeds/));
test('admin payout transitions are forward-only',()=>{assert.doesNotThrow(()=>assertPayoutTransition('pending','approved'));assert.throws(()=>assertPayoutTransition('paid','approved'),/cannot move/)});
