import { AlertCircle, CheckCircle2, Inbox, X } from 'lucide-react';

export function StatusBadge({status}){const colors={pending:'bg-amber-50 text-amber-800 ring-amber-200',confirmed:'bg-emerald-50 text-emerald-800 ring-emerald-200',completed:'bg-blue-50 text-blue-800 ring-blue-200',rejected:'bg-red-50 text-red-800 ring-red-200',cancelled:'bg-slate-100 text-slate-700 ring-slate-200'};return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold capitalize ring-1 ring-inset ${colors[status]||colors.cancelled}`}>{status}</span>}
export function Alert({type='error',children,onClose}){const success=type==='success';return <div role={success?'status':'alert'} className={`flex items-start gap-3 rounded-2xl border p-4 text-sm ${success?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-800'}`}>{success?<CheckCircle2 size={19}/>:<AlertCircle size={19}/>}<div className="flex-1">{children}</div>{onClose&&<button onClick={onClose} aria-label="Dismiss"><X size={18}/></button>}</div>}
export function EmptyState({icon:Icon=Inbox,title,description,action}){void Icon;return <div className="card px-6 py-16 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-teal-50 text-teal-700"><Icon/></span><h3 className="mt-5 font-serif text-2xl font-bold">{title}</h3>{description&&<p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{description}</p>}{action&&<div className="mt-6">{action}</div>}</div>}
export function SkeletonCards({count=3}){return <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3" aria-label="Loading"><span className="sr-only">Loading content</span>{Array.from({length:count},(_,i)=><div key={i} className="h-64 animate-pulse rounded-3xl bg-slate-200"/>)}</div>}
export function Dialog({title,children,onClose,size='max-w-xl'}){return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-slate-950/65 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose()}}><div className={`my-8 w-full ${size} rounded-[2rem] bg-white p-6 shadow-2xl sm:p-8`}><div className="mb-6 flex items-center justify-between"><h2 id="dialog-title" className="font-serif text-3xl font-bold">{title}</h2><button onClick={onClose} className="grid h-10 w-10 place-items-center rounded-full bg-slate-100" aria-label="Close dialog"><X size={18}/></button></div>{children}</div></div>}
export function ConfirmDialog({open,title,description,confirmLabel='Confirm',danger=false,busy=false,onConfirm,onClose}){if(!open)return null;return <Dialog title={title} onClose={onClose}><p className="leading-7 text-slate-600">{description}</p><div className="mt-7 flex justify-end gap-3"><button className="secondary-button" onClick={onClose}>Go back</button><button disabled={busy} onClick={onConfirm} className={danger?'inline-flex rounded-full bg-red-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-60':'primary-button'}>{busy?'Please wait...':confirmLabel}</button></div></Dialog>}
export function Toast({message,type='success',onClose}){if(!message)return null;return <div className="fixed bottom-5 right-5 z-[60] w-[min(90vw,380px)] shadow-2xl"><Alert type={type} onClose={onClose}>{message}</Alert></div>}
