import Payment from '../models/Payment.js';
import Refund from '../models/Refund.js';
import FinancialEvent from '../models/FinancialEvent.js';
import { initiateCheckout, processNotification, reconcile, safePayment } from '../services/payments/payment.service.js';
import { refundPayment } from '../services/payments/providers/payhere.provider.js';
import { toMinorUnits } from '../services/payments/money.js';

export const checkout = async(req,res,next)=>{try{res.status(201).json(await initiateCheckout({bookingId:req.params.bookingId,travelerId:req.user}));}catch(e){next(e)}};
export const notify = async(req,res)=>{try{await processNotification(req.body);res.type('text').send('OK');}catch(e){res.status(e.status||400).type('text').send('INVALID')}};
export const status = async(req,res,next)=>{try{const payment=await Payment.findOne({_id:req.params.id,...(req.userRole==='admin'?{}:{traveler:req.user})});if(!payment)return res.status(404).json({message:'Payment not found'});res.json(safePayment(payment));}catch(e){next(e)}};
export const listAdminPayments=async(req,res,next)=>{try{const filter=req.query.status?{status:req.query.status}:{};const payments=await Payment.find(filter).populate('booking','destination').populate('traveler','name email').populate('driver','fullName name').sort({createdAt:-1});res.json(payments.map(safePayment));}catch(e){next(e)}};
export const reconcilePayment=async(req,res,next)=>{try{const payment=await Payment.findById(req.params.id);if(!payment)return res.status(404).json({message:'Payment not found'});res.json(safePayment(await reconcile(payment)));}catch(e){next(e)}};
export const requestRefund=async(req,res,next)=>{try{const payment=await Payment.findById(req.params.id);if(!payment||!['paid','partially_refunded'].includes(payment.status))return res.status(409).json({message:'Payment is not refundable'});const amount=toMinorUnits(req.body.amount);const completed=await Refund.aggregate([{$match:{payment:payment._id,status:'completed'}},{$group:{_id:null,total:{$sum:'$amount'}}}]);if(amount+(completed[0]?.total||0)>payment.travelerTotal)return res.status(400).json({message:'Refund exceeds the paid amount'});const key=req.body.idempotencyKey?.trim();if(!key)return res.status(400).json({message:'Idempotency key is required'});let refund=await Refund.findOne({idempotencyKey:key});if(refund)return res.json(refund);refund=await Refund.create({payment:payment._id,booking:payment.booking,amount,currency:payment.currency,idempotencyKey:key,reason:req.body.reason||'',requestedBy:req.user,status:'processing'});await FinancialEvent.create({eventType:'refund_requested',entityType:'refund',entityId:refund._id,booking:payment.booking,actor:req.user,metadata:{amount}});try{const result=await refundPayment({providerPaymentId:payment.providerPaymentId,amount,reason:refund.reason});refund.status='completed';refund.providerRefundId=result.data?.refund_id||result.refund_id;refund.completedAt=new Date();await refund.save();const total=amount+(completed[0]?.total||0);payment.status=total===payment.travelerTotal?'refunded':'partially_refunded';payment.refundedAt=new Date();await payment.save();await FinancialEvent.create({eventType:'refund_completed',entityType:'refund',entityId:refund._id,booking:payment.booking,actor:req.user,metadata:{amount}});res.json(refund);}catch(error){refund.status='failed';refund.failureReason=error.message;await refund.save();throw error}}catch(e){next(e)}};
