import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Banknote, CalendarDays, Car, MapPin, Phone, Route, Star, Users } from 'lucide-react';
import api, { clearSession, getImageUrl } from '../api';

const statusStyles={pending:'bg-amber-50 text-amber-700',confirmed:'bg-emerald-50 text-emerald-700',completed:'bg-blue-50 text-blue-700',rejected:'bg-red-50 text-red-700',cancelled:'bg-slate-100 text-slate-600'};
const formatDate=(value)=>new Date(value).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
export default function Bookings(){
 const[bookings,setBookings]=useState([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[busy,setBusy]=useState('');const[reviewFor,setReviewFor]=useState(null);const navigate=useNavigate();
 const load=useCallback(async()=>{try{setBookings((await api.get('/bookings/mine')).data)}catch(e){if(e.response?.status===401){clearSession();navigate('/login')}else setError('Could not load your trips.')}finally{setLoading(false)}},[navigate]);
 useEffect(()=>{if(!localStorage.getItem('token'))navigate('/login');else load()},[load,navigate]);
 const cancel=async(b)=>{if(!window.confirm(`Cancel your trip to ${b.destination}?`))return;setBusy(b._id);try{await api.patch(`/bookings/${b._id}/cancel`);await load()}catch(e){setError(e.response?.data?.message||'Could not cancel booking')}finally{setBusy('')}};
 const active=bookings.filter((b)=>['pending','confirmed'].includes(b.status));const history=bookings.filter((b)=>!['pending','confirmed'].includes(b.status));
 const Card=({booking:b})=>{const name=b.driver?.fullName||b.driver?.name||'Driver unavailable';const image=b.driver?.profileImage||b.driver?.image;return <article className={`card overflow-hidden ${['cancelled','rejected'].includes(b.status)?'opacity-70':''}`}><div className="grid md:grid-cols-[220px_1fr]"><div className="h-52 bg-slate-100 md:h-full">{image?<img src={getImageUrl(image)} alt={name} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center"><Car/></div>}</div><div className="p-6 sm:p-7"><div className="flex justify-between gap-3"><div><span className={`rounded-full px-3 py-1 text-xs font-bold capitalize ${statusStyles[b.status]}`}>{b.status}</span><h3 className="mt-3 font-serif text-3xl font-bold">{b.destination}</h3></div><p className="text-xs text-slate-400">REF {b._id.slice(-6).toUpperCase()}</p></div><div className="mt-5 grid gap-3 text-sm text-slate-600 sm:grid-cols-2"><p className="flex gap-2"><CalendarDays size={17}/>{formatDate(b.startDate)} – {formatDate(b.endDate)}</p><p className="flex gap-2"><Route size={17}/>{b.numberOfDays} day(s)</p><p className="flex gap-2"><Users size={17}/>{b.partySize} traveler(s)</p><p className="flex gap-2"><Banknote size={17}/>LKR {Number(b.estimatedTotal).toLocaleString()}</p><p className="flex gap-2"><Car size={17}/>{name} · {b.driver?.vehicleModel||b.driver?.vehicleType}</p>{b.driver?.phoneNumber&&<p className="flex gap-2"><Phone size={17}/>{b.driver.phoneNumber}</p>}</div>{b.notes&&<p className="mt-5 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">“{b.notes}”</p>}<div className="mt-6 flex flex-wrap gap-4 border-t border-slate-100 pt-5">{['pending','confirmed'].includes(b.status)&&<button disabled={busy===b._id} onClick={()=>cancel(b)} className="text-sm font-bold text-red-700">{busy===b._id?'Cancelling...':'Cancel booking'}</button>}{b.status==='completed'&&!b.review&&<button onClick={()=>setReviewFor(b)} className="flex items-center gap-1 text-sm font-bold text-amber-700"><Star size={16}/>Review this journey</button>}{b.review&&<p className="text-sm font-bold text-amber-700">Your rating: {b.review.rating}/5</p>}</div></div></div></article>};
 return <main><section className="bg-[#eadfca] py-16"><div className="page-shell"><p className="eyebrow">Your travel dashboard</p><h1 className="mt-3 font-serif text-5xl font-semibold">My trips</h1><p className="mt-4 text-slate-600">Track journeys, costs, and verified reviews in one place.</p></div></section><section className="page-shell py-14">{error&&<p className="mb-7 rounded-2xl bg-red-50 p-4 text-red-700">{error}</p>}{loading?<p>Loading trips...</p>:!bookings.length?<div className="card py-20 text-center"><Route className="mx-auto text-teal-700" size={36}/><h2 className="mt-5 font-serif text-3xl font-bold">Your next story is waiting</h2><Link to="/trip-planner" className="primary-button mt-7"><MapPin size={17}/>Plan a trip</Link></div>:<div className="space-y-12">{!!active.length&&<section><h2 className="mb-5 font-serif text-3xl font-bold">Active trips</h2><div className="space-y-5">{active.map((b)=><Card key={b._id} booking={b}/>)}</div></section>}{!!history.length&&<section><h2 className="mb-5 font-serif text-3xl font-bold">Trip history</h2><div className="space-y-5">{history.map((b)=><Card key={b._id} booking={b}/>)}</div></section>}</div>}</section>{reviewFor&&<ReviewModal booking={reviewFor} onClose={()=>setReviewFor(null)} onSaved={async()=>{setReviewFor(null);await load()}}/>}</main>;
}
function ReviewModal({booking,onClose,onSaved}){const[rating,setRating]=useState(5);const[comment,setComment]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const submit=async(e)=>{e.preventDefault();setBusy(true);try{await api.post('/reviews',{bookingId:booking._id,rating,comment});await onSaved()}catch(err){setError(err.response?.data?.message||'Could not submit review')}finally{setBusy(false)}};return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><form onSubmit={submit} className="card w-full max-w-lg p-7"><p className="eyebrow">Verified journey</p><h2 className="mt-2 font-serif text-3xl font-bold">Review your driver</h2>{error&&<p className="mt-4 text-red-700">{error}</p>}<label className="mt-6 block"><span className="mb-2 block text-sm font-bold">Rating</span><select className="field" value={rating} onChange={(e)=>setRating(Number(e.target.value))}>{[5,4,3,2,1].map((x)=><option key={x} value={x}>{x} stars</option>)}</select></label><label className="mt-4 block"><span className="mb-2 block text-sm font-bold">Comment</span><textarea className="field min-h-28" maxLength="1000" value={comment} onChange={(e)=>setComment(e.target.value)}/></label><div className="mt-6 flex justify-end gap-3"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button disabled={busy} className="primary-button">{busy?'Submitting...':'Publish review'}</button></div></form></div>}
