import { useEffect, useMemo, useState } from 'react';
import { Heart, MapPin, Search } from 'lucide-react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import api, { getImageUrl, getStoredUser } from '../api';

export default function Destinations() {
  const [params] = useSearchParams();
  const [places, setPlaces] = useState([]); const [saved, setSaved] = useState(new Set()); const [query, setQuery] = useState(params.get('q') || ''); const [category, setCategory] = useState(params.get('category') || 'All'); const navigate = useNavigate();
  useEffect(() => { api.get('/places').then((r) => setPlaces(r.data)); if (getStoredUser()?.role === 'traveler') api.get('/favorites').then((r) => setSaved(new Set(r.data.map((x) => x.destination._id)))).catch(() => {}); }, []);
  const categories = useMemo(() => ['All', ...new Set(places.flatMap((p) => p.categories || []))], [places]);
  const filtered = places.filter((p) => (category === 'All' || p.categories?.includes(category)) && `${p.name} ${p.location} ${p.tags?.join(' ')}`.toLowerCase().includes(query.toLowerCase()));
  const toggle = async (id) => { if (!getStoredUser()) return navigate('/login'); if (saved.has(id)) { await api.delete(`/favorites/${id}`); setSaved(new Set([...saved].filter((x) => x !== id))); } else { await api.post(`/favorites/${id}`); setSaved(new Set([...saved, id])); } };
  return <main><section className="bg-[#102f27] py-20 text-white"><div className="page-shell"><p className="text-xs font-bold uppercase tracking-[.24em] text-amber-300">Island directory</p><h1 className="mt-4 font-serif text-5xl font-semibold">Find your kind of Sri Lanka.</h1><p className="mt-5 max-w-2xl text-white/65">Search cultural landmarks, wild landscapes, beaches, and hill-country escapes.</p></div></section><section className="page-shell py-12"><div className="card mb-9 grid gap-3 p-4 md:grid-cols-[1fr_240px]"><label className="relative"><Search className="absolute left-4 top-3.5 text-slate-400" size={18}/><input className="field !pl-11" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search name, location or interest"/></label><select className="field capitalize" value={category} onChange={(e)=>setCategory(e.target.value)}>{categories.map((x)=><option key={x}>{x}</option>)}</select></div><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">{filtered.map((p)=><article key={p._id} className="card group overflow-hidden"><div className="relative h-60 overflow-hidden"><img className="h-full w-full object-cover transition duration-500 group-hover:scale-105" src={getImageUrl(p.image)} alt={p.name}/><button onClick={()=>toggle(p._id)} aria-label="Save destination" className="absolute right-4 top-4 grid h-11 w-11 place-items-center rounded-full bg-white/90 text-rose-600"><Heart size={19} fill={saved.has(p._id)?'currentColor':'none'}/></button></div><div className="p-6"><p className="flex items-center gap-2 text-sm text-teal-700"><MapPin size={15}/>{p.location}</p><h2 className="mt-2 font-serif text-2xl font-bold">{p.name}</h2><p className="mt-3 line-clamp-2 text-sm leading-6 text-slate-500">{p.shortDescription || p.description || 'Discover this remarkable Sri Lankan destination.'}</p><Link to={`/destinations/${p.slug}`} className="primary-button mt-5 w-full">Explore destination</Link></div></article>)}</div>{!filtered.length&&<p className="card py-14 text-center text-slate-500">No destinations match these filters.</p>}</section></main>;
}
