import { useCallback, useEffect, useState } from 'react';
import { AlertCircle, CheckCircle2, Clock3, Landmark } from 'lucide-react';
import api from '../api';

const money = (value) => `LKR ${(Number(value || 0) / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const deadline = (date) => { const distance=new Date(date)-new Date();if(distance<=0)return 'Overdue';const hours=Math.ceil(distance/3600000);return hours<24?`${hours} hour(s) remaining`:`${Math.ceil(hours/24)} day(s) remaining`; };

export default function DriverEarnings() {
  const [data, setData] = useState({ standing:'clear', bankTransferInstructions:{}, commissions:[] });
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(''); const [reference, setReference] = useState({});
  const load = useCallback(async () => { try { setData((await api.get('/driver/commissions')).data); setError(''); } catch (err) { setError(err.response?.data?.message || 'Could not load commissions'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const submit = async (commission) => {
    if (!reference[commission._id]?.trim()) return setError('Enter your bank transfer reference');
    setBusy(commission._id); setSuccess('');
    try { await api.post(`/driver/commissions/${commission._id}/submit-payment`, { paymentReference:reference[commission._id] }); setSuccess('Payment reference submitted for administrator verification.'); await load(); }
    catch (err) { setError(err.response?.data?.message || 'Could not submit payment'); }
    finally { setBusy(''); }
  };
  const rows=data.commissions; const total=(statuses)=>rows.filter((item)=>!statuses||statuses.includes(item.status)).reduce((sum,item)=>sum+item.commissionAmount,0);
  const next=rows.filter((item)=>['due','overdue'].includes(item.status)).sort((a,b)=>new Date(a.dueAt)-new Date(b.dueAt))[0];
  const bank=data.bankTransferInstructions||{};
  return <main className="min-h-screen bg-[#f4f1e9]"><header className="bg-[#123a30] py-12 text-white"><div className="page-shell"><p className="text-xs font-bold uppercase tracking-[.22em] text-amber-300">Driver workspace</p><h1 className="mt-3 font-serif text-5xl font-semibold">Earnings & commissions</h1><p className="mt-3 text-white/65">Travelers pay tour prices directly to you. Completed platform bookings generate your Ceylon Explorer commission.</p></div></header><section className="page-shell py-10">
    {data.standing==='restricted'&&<div className="mb-6 flex gap-3 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-800"><AlertCircle/><div><b>Your account is restricted because a commission payment is overdue.</b><p className="text-sm">Submit the bank-transfer reference below. Existing trips and account access remain available while an administrator verifies it.</p></div></div>}
    {error&&<p className="mb-5 rounded-2xl bg-red-50 p-4 text-red-700">{error}</p>}{success&&<p className="mb-5 rounded-2xl bg-emerald-50 p-4 text-emerald-700">{success}</p>}
    <div className="mb-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Metric label="Completed tour value" value={money(rows.reduce((sum,item)=>sum+item.agreedTourPrice,0))}/><Metric label="Total platform commission" value={money(total())}/><Metric label="Outstanding commission" value={money(total(['due','overdue','payment_submitted']))}/><Metric label="Overdue commission" value={money(total(['overdue']))}/><Metric label="Paid commission" value={money(total(['paid']))}/><Metric label="Next payment deadline" value={next?deadline(next.dueAt):'No payment due'}/></div>
    {(bank.bankName||bank.accountNumber)&&<aside className="card mb-8 flex gap-4 p-6"><Landmark className="shrink-0 text-teal-700"/><div><h2 className="font-serif text-2xl font-bold">Bank-transfer instructions</h2><p className="mt-2 text-sm text-slate-600">{bank.bankName} · {bank.branch}</p><p className="font-bold">{bank.accountName} · {bank.accountNumber}</p><p className="mt-2 text-xs text-slate-500">Transfer the exact commission amount, then submit the bank reference on its invoice. A submission is not marked paid until an administrator verifies receipt.</p></div></aside>}
    {loading?<p>Loading commissions...</p>:<div className="space-y-5">{rows.map((commission)=><article className="card p-6" key={commission._id}><div className="flex flex-col justify-between gap-4 md:flex-row"><div><span className="rounded-full bg-teal-50 px-3 py-1 text-xs font-bold capitalize text-teal-800">{commission.status.replace('_',' ')}</span><h2 className="mt-3 font-serif text-2xl font-bold">{commission.booking?.destination}</h2><p className="mt-2 text-sm text-slate-500">REF {String(commission.booking?._id).slice(-6).toUpperCase()} · {new Date(commission.booking?.startDate).toLocaleDateString()} – {new Date(commission.booking?.endDate).toLocaleDateString()}</p><p className={`mt-1 text-sm font-bold ${new Date(commission.dueAt)<new Date()?'text-red-700':'text-amber-700'}`}>Due {new Date(commission.dueAt).toLocaleString()} · {deadline(commission.dueAt)}</p></div><div className="md:text-right"><p className="text-sm">Tour value {money(commission.agreedTourPrice)}</p><b className="text-xl text-teal-800">{money(commission.commissionAmount)} commission</b><p className="text-xs">{commission.commissionRateBps/100}%</p></div></div>{['due','overdue'].includes(commission.status)&&<div className="mt-5 grid gap-2 border-t pt-5 sm:grid-cols-[1fr_auto]"><input className="field" placeholder="Bank transfer reference" value={reference[commission._id]||''} onChange={(event)=>setReference({...reference,[commission._id]:event.target.value})}/><button disabled={busy===commission._id} onClick={()=>submit(commission)} className="primary-button shrink-0">{busy===commission._id?'Submitting...':'Submit payment'}</button></div>}{commission.status==='payment_submitted'&&<p className="mt-5 flex gap-2 text-sm text-amber-700"><Clock3 size={17}/>Submitted {new Date(commission.submittedAt).toLocaleString()} for admin verification: {commission.paymentReference}</p>}{commission.status==='paid'&&<p className="mt-5 flex gap-2 text-sm text-emerald-700"><CheckCircle2 size={17}/>Payment verified {commission.paidAt?new Date(commission.paidAt).toLocaleString():''}</p>}</article>)}{!rows.length&&<p className="card p-12 text-center text-slate-500">No commission invoices yet.</p>}</div>}
  </section></main>;
}
function Metric({label,value}){return <article className="card p-5"><p className="text-xs font-bold uppercase text-slate-400">{label}</p><b className="mt-2 block text-xl">{value}</b></article>}
