import { useCallback, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { CalendarDays, Check, Clock3, UserRound, X } from 'lucide-react';
import api, { clearSession, getImageUrl } from '../api';

const formatDate = (value) => new Date(value).toLocaleDateString(undefined, { day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC' });

export default function DriverDashboard({ view }) {
  const [profile, setProfile] = useState(null);
  const [bookings, setBookings] = useState([]);
  const [form, setForm] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [working, setWorking] = useState('');
  const navigate = useNavigate();
  const load = useCallback(async () => { try { const [profileResult, bookingResult] = await Promise.all([api.get('/driver/profile'), api.get('/driver/bookings')]); setProfile(profileResult.data); setBookings(bookingResult.data); setForm({ ...profileResult.data, languages: (profileResult.data.languages || []).join(', '), serviceAreas: (profileResult.data.serviceAreas || []).join(', ') }); } catch (requestError) { if ([401, 403].includes(requestError.response?.status)) { clearSession(); navigate('/login'); } else setError(requestError.response?.data?.message || 'Could not load the driver portal.'); } finally { setLoading(false); } }, [navigate]);
  useEffect(() => { load(); }, [load]);
  const transition = async (booking, action) => { setWorking(booking._id); setError(''); try { await api.patch(`/driver/bookings/${booking._id}/${action}`); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Could not update this booking.'); } finally { setWorking(''); } };
  const saveProfile = async (event) => { event.preventDefault(); setWorking('profile'); try { await api.put('/driver/profile', form); await load(); } catch (requestError) { setError(requestError.response?.data?.message || 'Could not update your profile.'); } finally { setWorking(''); } };
  const pending = bookings.filter((booking) => booking.status === 'pending');
  const upcoming = bookings.filter((booking) => ['accepted', 'confirmed'].includes(booking.status));
  const completed = bookings.filter((booking) => booking.status === 'completed');

  return <main className="min-h-screen bg-slate-100/70"><section className="border-b bg-white"><div className="page-shell py-10"><p className="eyebrow">Driver workspace</p><h1 className="mt-2 font-serif text-4xl font-bold">Welcome, {profile?.fullName || profile?.name || 'driver'}</h1><p className="mt-2 text-slate-500">Manage requests, upcoming journeys, and your professional profile.</p></div></section><div className="page-shell py-8"><nav className="mb-8 flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2"><Link className={`rounded-xl px-4 py-2 text-sm font-bold ${view === 'overview' ? 'bg-teal-800 text-white' : ''}`} to="/driver">Overview</Link><Link className={`rounded-xl px-4 py-2 text-sm font-bold ${view === 'bookings' ? 'bg-teal-800 text-white' : ''}`} to="/driver/bookings">Bookings</Link><Link className={`rounded-xl px-4 py-2 text-sm font-bold ${view === 'profile' ? 'bg-teal-800 text-white' : ''}`} to="/driver/profile">Profile</Link></nav>{error && <p className="mb-6 rounded-2xl bg-red-50 p-4 text-red-700">{error}</p>}{loading ? <div className="h-52 animate-pulse rounded-3xl bg-slate-200" /> : <>{view === 'overview' && <div className="space-y-8"><div className="grid gap-4 sm:grid-cols-3"><Metric icon={Clock3} label="Pending requests" value={pending.length} /><Metric icon={CalendarDays} label="Upcoming trips" value={upcoming.length} /><Metric icon={Check} label="Completed trips" value={completed.length} /></div><section><h2 className="mb-5 font-serif text-2xl font-bold">Requests requiring action</h2><BookingList bookings={pending} working={working} transition={transition} /></section></div>}{view === 'bookings' && <section><h2 className="mb-5 font-serif text-3xl font-bold">Assigned bookings</h2><BookingList bookings={bookings} working={working} transition={transition} /></section>}{view === 'profile' && form && <ProfileForm form={form} setForm={setForm} profile={profile} saving={working === 'profile'} onSubmit={saveProfile} />}</>}</div></main>;
}

function Metric({ icon, label, value }) { const MetricIcon = icon; return <article className="card flex items-center gap-4 p-5"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-teal-50 text-teal-700"><MetricIcon /></span><div><b className="text-3xl">{value}</b><p className="text-sm text-slate-500">{label}</p></div></article>; }
function BookingList({ bookings, working, transition }) { if (!bookings.length) return <div className="card py-12 text-center text-slate-500">No bookings in this section.</div>; return <div className="space-y-4">{bookings.map((booking) => { const canComplete = booking.status === 'confirmed' && new Date(booking.endDate) <= new Date(); return <article className="card p-6" key={booking._id}><div className="flex flex-col justify-between gap-4 md:flex-row"><div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold capitalize">{booking.status}</span><h3 className="mt-3 font-serif text-2xl font-bold">{booking.destination}</h3><p className="mt-2 text-sm text-slate-500">{formatDate(booking.startDate)} – {formatDate(booking.endDate)} · {booking.numberOfDays} days · {booking.partySize} guests</p><p className="mt-1 text-sm text-slate-500">Traveler: {booking.user?.name} ({booking.user?.email})</p><p className="mt-2 font-bold text-teal-800">LKR {Number(booking.estimatedTotal).toLocaleString()}</p></div><div className="flex items-start gap-2">{booking.status === 'pending' && <><button disabled={working === booking._id} onClick={() => transition(booking, 'accept')} className="primary-button !py-2"><Check size={16} /> Accept</button><button disabled={working === booking._id} onClick={() => transition(booking, 'reject')} className="secondary-button !py-2 !text-red-700"><X size={16} /> Reject</button></>}{canComplete && <button disabled={working === booking._id} onClick={() => transition(booking, 'complete')} className="primary-button !py-2">Mark completed</button>}</div></div></article>; })}</div>; }
function ProfileForm({ form, setForm, profile, saving, onSubmit }) { const update = (key) => (event) => setForm({ ...form, [key]: event.target.type === 'checkbox' ? event.target.checked : event.target.value }); return <form onSubmit={onSubmit} className="card mx-auto max-w-3xl p-7"><div className="mb-6 flex items-center gap-4">{(profile.profileImage || profile.image) ? <img src={getImageUrl(profile.profileImage || profile.image)} alt="Profile" className="h-20 w-20 rounded-2xl object-cover" /> : <UserRound />}<div><h2 className="font-serif text-3xl font-bold">Driver profile</h2><p className="text-sm capitalize text-slate-500">Verification: {profile.verificationStatus}</p></div></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Full name" value={form.fullName || ''} onChange={update('fullName')} /><Field label="Phone" value={form.phoneNumber || ''} onChange={update('phoneNumber')} /><Field label="Daily rate (LKR)" type="number" value={form.dailyRate || 0} onChange={update('dailyRate')} /><Field label="Experience (years)" type="number" value={form.yearsOfExperience || 0} onChange={update('yearsOfExperience')} /><Field label="Vehicle type" value={form.vehicleType || ''} onChange={update('vehicleType')} /><Field label="Vehicle model" value={form.vehicleModel || ''} onChange={update('vehicleModel')} /><Field label="Vehicle capacity" type="number" value={form.vehicleCapacity || 1} onChange={update('vehicleCapacity')} /><Field label="Languages (comma separated)" value={form.languages || ''} onChange={update('languages')} /><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Service areas</span><input className="field" value={form.serviceAreas || ''} onChange={update('serviceAreas')} /></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Bio</span><textarea className="field min-h-28" maxLength="1000" value={form.bio || ''} onChange={update('bio')} /></label><label className="flex items-center gap-3"><input type="checkbox" checked={Boolean(form.availability)} onChange={update('availability')} /> Available for new requests</label></div><button disabled={saving} className="primary-button mt-7">{saving ? 'Saving...' : 'Save profile'}</button></form>; }
function Field({ label, value, onChange, type = 'text' }) { return <label><span className="mb-2 block text-sm font-bold">{label}</span><input className="field" type={type} value={value} onChange={onChange} required /></label>; }
