import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import AuthLayout from '../components/AuthLayout';
import api, { saveSession } from '../api';

const initial = { name: '', email: '', password: '', confirmPassword: '', phoneNumber: '', vehicleType: '', vehicleModel: '', vehicleCapacity: 4, dailyRate: '', languages: '', serviceAreas: '', yearsOfExperience: 0, bio: '', image: null };

export default function DriverApply() {
  const [form, setForm] = useState(initial);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const navigate = useNavigate();
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); const payload = new FormData(); Object.entries(form).forEach(([key, value]) => payload.append(key, value)); try { const response = await api.post('/auth/register-driver', payload); saveSession(response.data); navigate('/driver'); } catch (requestError) { setError(requestError.response?.data?.message || 'Could not submit driver application.'); } finally { setSaving(false); } };
  const update = (key) => (event) => setForm({ ...form, [key]: event.target.files?.[0] || event.target.value });
  return <AuthLayout eyebrow="Driver onboarding" title="Join our local driver network" description="Create a connected driver account. Your profile remains private until an administrator verifies it."><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{error && <p className="rounded-2xl bg-red-50 p-4 text-sm text-red-700 sm:col-span-2">{error}</p>}<Field label="Full name" value={form.name} onChange={update('name')} /><Field label="Email" type="email" value={form.email} onChange={update('email')} /><Field label="Password" type="password" value={form.password} onChange={update('password')} /><Field label="Confirm password" type="password" value={form.confirmPassword} onChange={update('confirmPassword')} /><Field label="Phone number" value={form.phoneNumber} onChange={update('phoneNumber')} /><Field label="Daily rate (LKR)" type="number" value={form.dailyRate} onChange={update('dailyRate')} /><Field label="Vehicle type" value={form.vehicleType} onChange={update('vehicleType')} /><Field label="Vehicle model" value={form.vehicleModel} onChange={update('vehicleModel')} /><Field label="Vehicle capacity" type="number" value={form.vehicleCapacity} onChange={update('vehicleCapacity')} /><Field label="Experience (years)" type="number" value={form.yearsOfExperience} onChange={update('yearsOfExperience')} /><Field label="Languages" value={form.languages} onChange={update('languages')} placeholder="Sinhala, English" /><Field label="Service areas" value={form.serviceAreas} onChange={update('serviceAreas')} placeholder="Ella, Kandy" /><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Short bio</span><textarea className="field min-h-24" maxLength="1000" value={form.bio} onChange={update('bio')} /></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Profile photograph</span><input className="field" type="file" accept="image/*" onChange={update('image')} required /></label><button disabled={saving} className="primary-button sm:col-span-2">{saving ? 'Submitting...' : 'Submit driver application'}</button></form></AuthLayout>;
}
function Field({ label, value, onChange, type = 'text', placeholder = '' }) { return <label><span className="mb-2 block text-sm font-bold">{label}</span><input className="field" type={type} min={type === 'number' ? 0 : undefined} value={value} onChange={onChange} placeholder={placeholder} required /></label>; }
