import mongoose from 'mongoose';
import Booking from '../models/Booking.js';import BookingLock from '../models/BookingLock.js';import Commission from '../models/Commission.js';import Driver from '../models/Driver.js';import FinancialEvent from '../models/FinancialEvent.js';
import { determineCommissionStanding } from './commissionRules.js';
const hours=(name,fallback)=>Number(process.env[name]||fallback)*3600000;
export const tourEndTimestamp=(date)=>{const day=new Date(date).toISOString().slice(0,10);return new Date(`${day}T18:29:59.999Z`)};
export const commissionDueAt=(date)=>new Date(tourEndTimestamp(date).getTime()+hours('COMMISSION_PAYMENT_WINDOW_HOURS',24));
const IDEMPOTENT_EVENTS=new Set(['commission_created','commission_due','commission_overdue']);
const audit=(eventType,commission,metadata={},actor,session)=>IDEMPOTENT_EVENTS.has(eventType)
  ? FinancialEvent.updateOne({eventKey:`${eventType}:${commission._id}`},{$setOnInsert:{eventKey:`${eventType}:${commission._id}`,eventType,entityType:'commission',entityId:commission._id,commission:commission._id,booking:commission.booking,driver:commission.driver,actor,metadata}},{upsert:true,session})
  : FinancialEvent.create([{eventType,entityType:'commission',entityId:commission._id,commission:commission._id,booking:commission.booking,driver:commission.driver,actor,metadata}],{session}).then(([event])=>event);

export const processOverdueCommissions=async(driverId)=>{const filter={status:'due',dueAt:{$lt:new Date()},...(driverId&&{driver:driverId})};const rows=await Commission.find(filter);for(const commission of rows){commission.status='overdue';commission.overdueAt=commission.overdueAt||new Date();await commission.save();await audit('commission_overdue',commission)}if(driverId)await refreshDriverCommissionStanding(driverId);else{const restrictedIds=await Commission.distinct('driver',{$or:[{status:'overdue'},{status:'payment_submitted',overdueAt:{$ne:null}}]});for(const id of new Set([...rows.map(x=>String(x.driver)),...restrictedIds.map(String)]))await refreshDriverCommissionStanding(id)}return rows.length};
export const refreshDriverCommissionStanding=async(driverId)=>{await processOverdueCommissionsWithoutRefresh(driverId);const commissions=await Commission.find({driver:driverId,status:{$in:['pending','due','payment_submitted','overdue']}}).select('status overdueAt');const standing=determineCommissionStanding(commissions);const driver=await Driver.findById(driverId);if(driver&&driver.commissionStanding!==standing){const previous=driver.commissionStanding;driver.commissionStanding=standing;if(standing==='restricted'){driver.availabilityBeforeRestriction=driver.availability;driver.availability=false}else if(previous==='restricted'&&driver.availabilityBeforeRestriction!==undefined){driver.availability=driver.availabilityBeforeRestriction;driver.availabilityBeforeRestriction=undefined}await driver.save();await FinancialEvent.create({eventType:standing==='restricted'?'driver_restricted':'driver_reactivated',entityType:'driver',entityId:driver._id,driver:driver._id,metadata:{previous,standing}})}return standing};
const processOverdueCommissionsWithoutRefresh=async(driverId)=>{const rows=await Commission.find({driver:driverId,status:'due',dueAt:{$lt:new Date()}});for(const c of rows){c.status='overdue';c.overdueAt=c.overdueAt||new Date();await c.save();await audit('commission_overdue',c)}return rows.length};

export const completeBookingAndGenerateCommission=async({bookingId,source,actor,now=new Date()})=>{const booking=await Booking.findById(bookingId);if(!booking)throw Object.assign(new Error('Booking not found'),{status:404});const ended=tourEndTimestamp(booking.endDate);if(now<ended)throw Object.assign(new Error('The tour can only be completed after its end time'),{status:409});if(!['confirmed','completed'].includes(booking.status))throw Object.assign(new Error(`Booking cannot be completed from ${booking.status}`),{status:409});const existing=await Commission.findOne({booking:booking._id});if(booking.status==='completed'&&existing)return{booking,commission:existing};const session=await mongoose.startSession();let commission;try{await session.withTransaction(async()=>{const updated=await Booking.findOneAndUpdate({_id:booking._id,status:'confirmed'},{$set:{status:'completed',completedAt:now,completionSource:source}},{new:true,session});if(!updated){commission=await Commission.findOne({booking:booking._id}).session(session);return}await BookingLock.deleteMany({booking:booking._id}).session(session);[commission]=await Commission.create([{booking:booking._id,driver:booking.driver,agreedTourPrice:booking.agreedTourPrice??booking.driverSubtotal,commissionRateBps:booking.commissionRateBps??booking.platformCommissionRateBps,commissionAmount:booking.commissionAmount??booking.platformCommissionAmount,currency:booking.currency||'LKR',status:'due',tourEndedAt:ended,dueAt:commissionDueAt(booking.endDate)}],{session});await audit('commission_created',commission,{completionSource:source},actor,session);await audit('commission_due',commission,{},actor,session)});await refreshDriverCommissionStanding(booking.driver);return{booking:await Booking.findById(booking._id),commission}}finally{await session.endSession()}};
export const autoCompleteEligibleBookings=async()=>{const rows=await Booking.find({status:'confirmed'});let count=0;for(const booking of rows){const eligibleAt=new Date(tourEndTimestamp(booking.endDate).getTime()+hours('AUTO_COMPLETE_GRACE_HOURS',6));if(new Date()>=eligibleAt){await completeBookingAndGenerateCommission({bookingId:booking._id,source:'automatic'});count++}}return count};
export const recordCommissionAudit=audit;
